// Generated by CoffeeScript 1.9.3
// Modified for MV3: removed IIFE wrapper so sock/tryConnect are module-level,
// added chrome.alarms keepalive to prevent service worker termination.
importScripts('utils.js');

var sock = null;
var slice = [].slice;

var handleRequest = function(s) {
  return function(arg) {
    var data, i, len, obj, path, property, ref, request;
    data = arg.data;
    request = JSON.parse(data);
    if (request.args == null) {
      request.args = [];
    }
    path = request.path;
    if (path == null) {
      return s.send(JSON.stringify(extend(request, {
        error: "requests does not contain a path"
      })));
    } else if (path === "ping") {
      return s.send(JSON.stringify(extend(request, {
        response: ["ok"],
        error: false
      })));
    } else {
      // obj = window;
      obj = self;
      ref = path.split(".");
      for (i = 0, len = ref.length; i < len; i++) {
        property = ref[i];
        try {
          obj = obj[property];
        } catch (_error) {
          s.send(JSON.stringify(extend(request, {
            error: "incorrect path: " + path
          })));
          return;
        }
      }
      switch (typeof obj) {
        case "function":
          return obj.apply(null, slice.call(request.args).concat([function() {
            var response;
            response = 1 <= arguments.length ? slice.call(arguments, 0) : [];
            return s.send(JSON.stringify(extend(request, {
              response: response,
              error: false
            })));
          }]));
        default:
          return s.send(JSON.stringify(extend(request, {
            response: [obj],
            error: false
          })));
      }
    }
  };
};

var reTryConnect = function() {
  console.log("disconnected, retry connection in " + config.timeout + "ms...");
  return setTimeout(tryConnect, config.timeout);
};

var tryConnect = function() {
  var reTryFunction, url;
  reTryFunction = makeIdempotent(reTryConnect);
  try {
    url = "ws://" + config.host + ":" + config.port + "/";
    sock = new WebSocket(url);
  } catch (_error) {
    reTryFunction();
    return;
  }
  sock.onerror = sock.onclose = reTryFunction;
  sock.onmessage = handleRequest(sock);
  return console.log("connected: " + url);
};

tryConnect();

chrome.alarms.create('keepAlive', { periodInMinutes: 0.4 });
chrome.alarms.onAlarm.addListener(function(alarm) {
  if (alarm.name === 'keepAlive') {
    if (!sock || sock.readyState !== WebSocket.OPEN) {
      tryConnect();
    }
  }
});
